config/routes.rb
Rails.application.routes.draw do
  resources :rules
  resources :videos
  resources :badges
  resources :users
  resources :companies


  get '/log_in/:id' => 'application#log_in', as: :log_in
  get '/log_out' => 'application#log_out', as: :log_out

  get 'video/:id/play',      to: 'videos#play',      as: :video_play
  get 'video/:id/register',  to: 'videos#register',  as: :video_register

  root 'companies#index'

end

app/models/video.rb
class Video < ActiveRecord::Base
	acts_as_decorables
	
  has_many :user_videos
  has_many :users, through: :user_videos

  validates_presence_of :name
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  include VideosHelper

  before_action :set_video, only: [:register, :play, :show, :edit, :update, :destroy]


  # GET /videos
  # GET /videos.json
  def index
    @videos = Video.all
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
    current_user.try :watch_video, @video
  end

  # GET /videos/new
  def new
    @video = Video.new
  end

  # GET /videos/1/edit
  def edit
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new(video_params)

    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: 'Video was successfully created.' }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1
  # PATCH/PUT /videos/1.json
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
        format.json { render :show, status: :ok, location: @video }
      else
        format.html { render :edit }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to videos_url, notice: 'Video was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  def register
    pDebug('register')
    # from http://codegolf.stackexchange.com/questions/4707/outputting-ordinal-numbers-1st-2nd-3rd
    def o(n)n.to_s+%w{th st nd rd}[n/10%10==1||n%10>3?0:n%10]end

    uv = UserVideo.where( :user_id => current_user.id, :video_id => @video.id)
    if uv.empty?
      uv = UserVideo.new
      uv.user_id    = current_user.id
      uv.video_id   = @video.id
      uv.iterations = 1

      if uv.save
        update_user_badges
        flash[:success] = "Video registered to #{current_user.name} - 1st viewing."
        render :json => { :message => "Video registered to #{current_user.name} - 1st viewing." } 
      else
        pDebug("Register error: #{uv.errors.messages}")
        render :json => { :message => "Couldn't register video to #{current_user.name}; error=#{uv.errors.messages}" } 
      end
    else
      uv[0].iterations += 1
      if uv[0].save
        update_user_badges
        msg = "That was the #{o(uv[0].iterations)} viewing of this video"
        flash[:success] = msg
        render :json => { :message => msg} 
      else
        pDebug("Register error: #{uv.errors.messages}")
        render :json => { :message => "Couldn't register video to #{current_user.name}; error=#{uv.errors.messages}" } 
      end
    end
  end


  def play
    pDebug('play')
    if current_user.nil?
      flash[:danger] = "* Need to be logged in."
      redirect_to videos_path
    else
      @video = @video.decorate(view_context)
      pDebug(@video.inspect)
    end
  end








  private

  
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def video_params
      params.require(:video).permit(:name)
    end


    def update_user_badges
      pDebug('update_user_badges')
      awarded = ''
      Rule.all.each do |rule|
        UserVideo.where( :user_id => current_user.id ).each do |uv|
          if in_range(uv.iterations, rule)
            awarded = Badge.find_by( :name => rule.badge_name)  

            if UserBadge.where( :badge_id => awarded.id, :user_id => current_user.id).size > 0
              break
            end

            ub = UserBadge.new
            ub.badge_id = awarded.id
            ub.user_id  = current_user.id
            if ub.save
              pDebug("User badge awarded and saved in UserBadge")
            else
              pDebug("Error in saving UserBadge: #{ub.errors.messages}")
            end
            break
          end
        end
      end
    end


    def in_range( iterations, rule )
      if rule.video_name == '*'  
        my_viewings = 0
        UserVideo.where( :user_id => current_user.id ).each do |uv|
          my_viewings += uv.iterations
        end

        if rule.view_count == 0   # view all videos
          return UserVideo.where( :user_id => current_user.id).count >= Video.count
        else
          return my_viewings >= rule.view_count
        end

      else                         
        badge = Badge.find_by( :name => rule.badge_name )
        video = Video.find_by( :name => rule.video_name )

        uv = UserVideo.where( :user_id => current_user.id, :video_id => video.id )
        if uv.empty?
          return false
        else
          return uv[0].iterations == rule.view_count
        end
      end
    end


end

app/helpers/videos_helper.rb
module VideosHelper

end

app/views/videos/_form.html.erb
<%= form_for(@video) do |f| %>
  <% if @video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@video.errors.count, "error") %> prohibited this video from being saved:</h2>

      <ul>
      <% @video.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field" style='margin-top: 10px;'>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>


  <div class="actions" style='margin-top: 50px;'>
    <%= f.submit %>
  </div>
<% end %>

app/views/videos/edit.html.erb
<h1>Editing video</h1>

<%= render 'form' %>

<%= link_to 'Show', @video %> |
<%= link_to 'Back', videos_path %>

app/views/videos/index.html.erb
<script type="text/javascript">

  $( document ).ready(function() {

    $('[id^=video_]').on('click', function() {
        var tmp      =  $(this).attr('id');
        var match    = /^video_(\d+)$/.exec(tmp);
        var video_id = RegExp.$1;

        // kludge, I know...
        tmp = '<%= video_register_path(999) %>'
        var url = tmp.replace("999", video_id);

        $.ajax({
            type: "GET",
            url: url,
            success: function(res)  {
                console.log( res.message );
                $('#iterations').html( res.iterations );
            }
        });
    });
  });

</script>


<h1>Listing videos</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <% if current_user %>
        <th>Viewings</th>
      <% end %>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @videos.each do |video| %>
      <tr>
        <td><%= video.name %></td>
        <% if current_user %>
          <td><%= current_user.iterations(video) %></td>
        <% end %>
        <td><%= link_to 'play', video_play_path(video.id), :class => "play_button", :id => "video_#{video.id}" %></td>

        <td><%= link_to 'Show', video %></td>
        <td><%= link_to 'Edit', edit_video_path(video) %></td>
        <td><%= link_to 'Destroy', video, method: :delete, data: { confirm: 'Are you sure?' } %></td>


      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Video', new_video_path %>

app/views/videos/new.html.erb
<h1>New video</h1>

<%= render 'form' %>

<%= link_to 'Back', videos_path %>

app/views/videos/play.html.erb
<p id="notice"><%= notice %></p>

<%= container_tag do %>
  <h1><%= @video.display %></h1>
<% end %>


<%= container_tag id: 'links', class: 'text-center' do %>
  <%= btn_to 'Edit', edit_video_path(@video) %>
  <%= btn_to 'Back', videos_path %>
<% end %>

app/views/videos/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @video.name %>
</p>

<% if current_user %>
  <p>
    <strong>Watched?:</strong>
    <%= current_user.watched? @video %>
  </p>
<% end %>

<%= link_to 'Edit', edit_video_path(@video) %> |
<%= link_to 'Back', videos_path %>