config/routes.rb
Rails.application.routes.draw do
  resources :rules
  resources :videos
  resources :badges
  resources :users
  resources :companies


  get '/log_in/:id' => 'application#log_in', as: :log_in
  get '/log_out' => 'application#log_out', as: :log_out

  get 'video/:id/play',      to: 'videos#play',      as: :video_play
  get 'video/:id/register',  to: 'videos#register',  as: :video_register

  root 'companies#index'

end

app/models/company.rb
class Company < ActiveRecord::Base
	acts_as_decorables
	
  has_many :users
	validates_presence_of 	:name

  def to_s
    name
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  include CompaniesHelper
  
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
    @company = @company.decorate(view_context)
    @users = User.where( :company_id => @company.id)
    @badges = get_company_badges(@company)
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name)
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper

  def get_company_badges(co)
  	tmp    = []
  	badges = []

  	co.users.each do |u| 
  		u.badges.each do |b| 
  			tmp.push( b.name )
  		end 
  	end

  	tmp.uniq.each do |b| 
  		badges.push( Badge.find_by(:name => b).fa_symbol )
  	end

  	return badges
  end
  
end

app/views/companies/_form.html.erb
<%= form_for(@company) do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% @company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing company</h1>

<%= render 'form' %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<h1>Listing companies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= company.name %></td>
        <td><%= link_to 'Show', company %></td>
        <td><%= link_to 'Edit', edit_company_path(company) %></td>
        <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Company', new_company_path %>

app/views/companies/new.html.erb
<h1>New company</h1>

<%= render 'form' %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

  <div class='container' style='border-bottom: 1px solid lightgray;'>
	 <span style='font-size: 2em;'>Company-Owned Badge(s): </span>

	 	<% if @badges.empty? %>
	 		<span class='symbol'>none</span> 
	 	<% else %>
		  <% @badges.each do |b| %>
		  	<span style='font-size: .3em;' class='symbol'><%= fa_icon b %></span> 
			<% end %>
		<% end %>
	</div>

<%= container_tag do %>
  <h2><%= @company.employees %></h2>
<% end %>

<%= container_3_tag @users, rows: {cols: {class: 'text-center'}} do |u| %>
  <h3><%= u.name %></h3>
  <% u.badges.each do |b| %>
    <span class='symbol'><%= fa_icon b.fa_symbol %></span> 
	<% end %>
<% end %>

<%= container_tag id: 'links', class: 'text-center' do %>
  <%= btn_to 'Edit', edit_company_path(@company) %>
  <%= btn_to 'Back', companies_path %>
<% end %>